### ISSUE TITLE
AttributeError: module 'psutil_windows' has no attribute 'proc_name'

### ISSUE THREAD

**Issue by phairplay** [HTPC-Manager/HTPC-Manager#60]
### Reporting Issues:

**Use proper markdown syntax to structure your post (i.e. code/log in code blocks).**

**Make sure you provide the following information below:**
- [ ] HTP-MANAGER

- [ ] master

- [ ] 	bee309ba7d435a354a833b7181813fe5b671703f

- [ ] Windows 10

- [ ] 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]

- [ ] Enable psutil

- [ ] nothing showing yet an error has appeared in the log 

- [ ] show the process of my machine

- [ ] unsure

- [ ] What are your (relevant) settings?

- [ ] **FULL** log (not just a few lines!) that has the error.
<details><summary>Expand log</summary>

```
2022-09-26 22:00:12 :: root :: INFO :: Welcome to the Python 3 port of Hellowlol's HTPC Manager fork
2022-09-26 22:00:12 :: root :: INFO :: Loglevel set to info
2022-09-26 22:00:12 :: htpc.updater :: INFO :: Using GitUpdater engine
2022-09-26 22:00:12 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2022-09-26 22:00:12 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2022-09-26 22:00:12 :: modules.newznab :: WARNING :: No configured Indexers.
2022-09-26 22:02:04 :: root :: INFO :: Welcome to the Python 3 port of Hellowlol's HTPC Manager fork
2022-09-26 22:02:04 :: root :: INFO :: Loglevel set to info
2022-09-26 22:02:04 :: htpc.updater :: INFO :: Using GitUpdater engine
2022-09-26 22:02:04 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2022-09-26 22:02:04 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2022-09-26 22:02:04 :: modules.newznab :: WARNING :: No configured Indexers.
2022-09-27 16:10:26 :: root :: INFO :: Welcome to the Python 3 port of Hellowlol's HTPC Manager fork
2022-09-27 16:10:26 :: root :: INFO :: Loglevel set to info
2022-09-27 16:10:26 :: htpc.updater :: INFO :: Using GitUpdater engine
2022-09-27 16:10:26 :: apscheduler.scheduler :: INFO :: Added job "Updater.update_needed" to job store "default"
2022-09-27 16:10:26 :: modules.kodi :: WARNING :: No configured kodi-Servers.
2022-09-27 16:10:26 :: modules.newznab :: WARNING :: No configured Indexers.
2022-09-27 16:10:27 :: htpc.server :: INFO :: Starting up webserver
2022-09-27 16:10:27 :: cherrypy.error :: INFO :: [27/Sep/2022:16:10:27] ENGINE Listening for SIGTERM.
2022-09-27 16:10:27 :: cherrypy.error :: INFO :: [27/Sep/2022:16:10:27] ENGINE Bus STARTING
2022-09-27 16:10:27 :: cherrypy.error :: INFO :: [27/Sep/2022:16:10:27] ENGINE Set handler for console events.
2022-09-27 16:10:28 :: cherrypy.error :: INFO :: [27/Sep/2022:16:10:28] ENGINE Serving on http://0.0.0.0:8085
2022-09-27 16:10:28 :: cherrypy.error :: INFO :: [27/Sep/2022:16:10:28] ENGINE Bus STARTED
2022-09-27 16:10:54 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH * HTTP/1.0
2022-09-27 16:10:54 :: modules.plex :: ERROR :: Unable to get players
2022-09-27 16:11:17 :: modules.plex :: INFO :: Sending discovery message: M-SEARCH * HTTP/1.0
2022-09-27 16:11:17 :: modules.plex :: ERROR :: Unable to get players
2022-09-27 16:11:21 :: cherrypy.error.1417175344856 :: ERROR :: [27/Sep/2022:16:11:21] HTTP 
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Python37\lib\site-packages\cherrypy\lib\jsontools.py", line 59, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "C:\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\HTPC-Manager3\modules\stats.py", line 288, in processes
    p.dict['name'] = psutil._psplatform.cext.proc_name(p.pid)
AttributeError: module 'psutil_windows' has no attribute 'proc_name'
```
</details>

I have all the required packages installed. could you please help me understand how to resolve this issue. the original Hellow HTPC manager works fine.

many thanks

**Comment by MichaIng** [comment]
Many thanks for reporting.

There is a very old for obtaining process names on Windows. Probably it is obsolete, at least the docs indicate that it should work with the regular way on Windows as well: https://psutil.readthedocs.io/en/latest/index.html?highlight=proc_name#psutil.Process.name

Can you try to remove these there lines from `stats.py`: https://github.com/HTPC-Manager/HTPC-Manager/blob/6200e79/modules/stats.py#L285-L287

**Comment by phairplay** [comment]
Amazing!
removing the lines got it working
thank you so much for working in this. I use this daily to monitor my headless pc via mobile devices :)

**Comment by MichaIng** [comment]
Great, the process names are shown correctly?
