### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by gmiranda** [HTPC-Manager/HTPC-Manager#9]
- [ ] Branch
master2

- [ ] Commit hash
a37460bda9ce89fde5c40f8fd0c442a4b216716e

- [ ] Operating system
Lubuntu 18.04

- [ ] Python version
3.6.9

- [ ] What you did?
Just run as a non-root user, with a configured kodi server and the recent episodes slideshow enabled in the main page.

- [ ] What happened?
`TypeError: Unicode-objects must be encoded before hashing
2020-09-01 17:29:54 :: cherrypy.error.140383936514984 :: ERROR :: [01/Sep/2020:17:29:54] HTTP
Traceback (most recent call last):
  File "/home/hefe/HTPC-Manager/venv/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/hefe/HTPC-Manager/venv/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/hefe/HTPC-Manager/venv/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/hefe/HTPC-Manager/modules/kodi.py", line 326, in GetThumb
    return get_image(url, h, w, o, mode, self.auth())
  File "/home/hefe/HTPC-Manager/htpc/helpers.py", line 67, in get_image
    imghash = hashlib.md5(url).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
`

- [ ] What you expected?

- [ ] How can we reproduce your issue?

- [ ] What are your (relevant) settings?

- [ ] Include a link to your **FULL** (not just a few lines!) log file that has the error. Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.

#### Link to log:

**Comment by MichaIng** [comment]
CodeFactor/Bandit also complains about weak MD5 hashing, but since this is only to get unique thumbs file names, this can be ignored, I guess.
This should work: https://stackoverflow.com/a/22505259
```
get_image imghash = hashlib.md5(url.encode('utf-8')).hexdigest()
```

**Comment by rkorn86** [comment]
Same error in Module CouchPotato:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/htpcmanager/modules/couchpotato.py", line 187, in GetImage
    tl = [(hashlib.md5(u).hexdigest(), u) for u in x]
  File "/app/htpcmanager/modules/couchpotato.py", line 187, in <listcomp>
    tl = [(hashlib.md5(u).hexdigest(), u) for u in x]
```

`couchpotato.py:187` needs to be `tl = [(hashlib.md5(u.encode('utf-8')).hexdigest(), u) for u in x]`

Please re-open & fix.

**Comment by gmiranda** [comment]
> 
> 
> Same error in Module CouchPotato:
> 
> 
> `couchpotato.py:187` needs to be `tl = [(hashlib.md5(u.encode('utf-8')).hexdigest(), u) for u in x]`
> 
> Please re-open & fix.

I'm not using CouchPotato so I don't have a quick way of testing it. If that fix works for you, you're more than welcome to submit a pull request!

**Comment by MichaIng** [comment]
Looks good, yes please send a PR. I can test it locally at short notice.

**Comment by MichaIng** [comment]
Fix has been tested and merged.
